### PR TITLE
Use CustomerGroupChoiceType instead of EntityType

### PR DESCRIPTION
**Pull request by tavy315**
This should fix `Expected value of type "App\Entity\Customer\CustomerGroup" for association field "Brille24\SyliusTierPricePlugin\Entity\TierPrice#$customerGroup", got "Sylius\Component\Customer\Model\CustomerGroup" instead.` exception when using own CustomerGroup entity.

### CODE REVIEW

**Comment by mamazu** [comment]
You're customer option group should implement the interface set in entity. The fix you are proposing will make it difficult to override the customer group.

**Comment by tavy315** [comment]
Sylius\Bundle\CustomerBundle\Form\Type\CustomerGroupChoiceType is the one used on "Edit customer" page (ex: /admin/customers/1/edit). And I am overridding the customer group entity and it works just fine (both on "Edit customer" and "Tier prices" pages).

**Comment by mamazu** [comment]
Then I don't get what the difference is. I would stick to the type that Sylius provides.

**Comment by tavy315** [comment]
I am using Sylius Standard Edition version 1.7 and it comes with [`App\Entity\Customer\CustomerGroup`](https://github.com/Sylius/Sylius-Standard/blob/master/src/Entity/Customer/CustomerGroup.php). 

I am getting that exception `Expected value of type "App\Entity\Customer\CustomerGroup" for association field "Brille24\SyliusTierPricePlugin\Entity\TierPrice#$customerGroup", got "Sylius\Component\Customer\Model\CustomerGroup" instead.`

Not sure if you agree with the fix or not, but I created a new repository with fresh install of Sylius and plugin if you want to test. [https://github.com/tavy315/sylius-standard-tier-prices]

That's why I proposed this fix, to use the type that Sylius provides [`Sylius\Bundle\CustomerBundle\Form\Type\CustomerGroupChoiceType`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerType.php#L27).

**Comment by mamazu** [comment]
This looks like an error in your mapping of doctrine. If you have made changes to your CustomerGroup and want use your own CustomerGroup, you need to override the Tierprice mapping for the CustomerGroup.

**Comment by tavy315** [comment]
I'm using Sylius' defaults, which you can see (https://github.com/Sylius/Sylius-Standard/blob/master/config/packages/_sylius.yaml#L94). By default, App\Entity\Customer\CustomerGroup extends Sylius\Component\Customer\Model\CustomerGroup.

I haven't done any changes or customizations to Sylius' defaults, that's why I provided a sample on (https://github.com/tavy315/sylius-standard-tier-prices).

**Comment by mamazu** [comment]
I just checked out your project and I was reading the merge request wrong the entire time. Of course you are right we should use the `CustomerGroupChoiceType`. However I don't know if this solution can also account for the fact that the `customerGroup` can be null.

**Pull request merged**
